### ISSUE TITLE
Frends.SFTP.ListFiles, Frends.SFTP.ReadFile and Frends.SFTP.WriteFile should support .NET Standard 2.0

### ISSUE THREAD

**Issue by tuukka-kataja** [FrendsPlatform/Frends.SFTP#122]
The Frends.SFTP.ListFiles, Frends.SFTP.ReadFile and Frends.SFTP.WriteFile tasks should support .NET Standard 2.0 in addition to .NET 6. The tasks Frends.SFTP.DownloadFiles and Frends.SFTP.UploadFiles already have the support. On a quick glance, there seems to be no obvious reason for the lack of support for .NET Standard 2.0 for the rest of the tasks.

For us, the .NET Standard 2.0 support would greatly simplify our transition away from Frends.Cobalt.

**Comment by RikuVirtanen** [comment]
The ListFiles, ReadFiles and WriteFiles tasks are part of the new official tasks project where we are only targeting .net6. The only reason for DownloadFiles and UploadFiles were multitargeted was to help the Cobalt migrate, because they handle all the Cobalt's SFTP transfers. To get the new official task you need to upgrade to newer Frends version, atleast 5.5 and add a crossplatform agent.
