### ISSUE TITLE
SFTP.DownloadFiles - new feature

### ISSUE THREAD

**Issue by RikuVirtanen** [FrendsPlatform/Frends.SFTP#193]
Task should check the file checksum before deleting the file if that operation is selected. The file checksum could also be returned from the Task.

**Comment by OlavReppen** [comment]
I was the one who requested this.
What I meant was that I wish that you either check the md5 checksum after downloading so that it is verified as uncorrupted during transfer. Or that the md5 checksum is presented in SFTP.ListFiles so that I can do this validation myself before deleting the source file using SFTP.DeleteFile.

**Comment by RikuVirtanen** [comment]
Calling the functions needed to get the checksum isn't supported by most SFTP servers. Additionally SSH has similar error control, so it is highly unlikely that corruption occurs.
https://stackoverflow.com/questions/30056566/how-to-perform-checksums-during-a-sftp-file-transfer-for-data-integrity
